-- T?o các b?ng (5 b?ng)
-------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------- Cau 1
-------------------------------------------------------------------------------------------------------------------------------------------------------

-- B?ng ng??i dùng
CREATE TABLE BT_Person
(
    "id" NUMBER(13,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, -- id t? t?ng
    username VARCHAR(20) NOT NULL UNIQUE, -- Tài kho?n 
    "password" VARCHAR(128) NOT NULL, -- M?t kh?u l?u hash
    "name" NVARCHAR2(128) DEFAULT '1' NOT NULL, -- H? tên
    gender NUMBER(1,0) DEFAULT '0' NOT NULL, -- Gi?i tính 1 là nam 0 là n?
    phonenumber CHAR(10) UNIQUE NOT NULL, -- S? ?i?n tho?i
    dateofbirth DATE DEFAULT SYSDATE NOT NULL, -- Ngày sinh
    avatar VARCHAR(128) DEFAULT 'DEFAULT' NOT NULL, -- L?u ???ng d?n ?nh ??i di?n ng??i dùng
    
    -- Khóa chính
    CONSTRAINT BT_Person_PK PRIMARY KEY ("id"),
    
    -- Các c?t
    CONSTRAINT BT_Person_username_length_greaterThan2 CHECK (LENGTH(username)>2),
    CONSTRAINT BT_Person_password_length_greaterThan2 CHECK (LENGTH("password")>2),
    CONSTRAINT BT_Person_name_length_greaterThan2 CHECK (LENGTH("name")>2),
    CONSTRAINT BT_Person_valid_phonenumber CHECK (REGEXP_LIKE(phonenumber,'^0\d{9}$'))
);

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('admin', '1234', 'Administrator', '1', '0000000000', DATE'2020-10-04', 'anh-avatar-supreme-dep-lam-dai-dien-facebook.jpg');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('user1', '1234', 'User1', '1', '0000000001', DATE'2020-10-04', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('user2', '1234', 'User2', '0', '0000000002', DATE'2020-10-04', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('user3', '1234', 'User3', '0', '0000000003', DATE'2020-10-04', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('user4', '1234', 'User4', '0', '0000000004', DATE'2020-10-04', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('user5', '1234', 'User5', '0', '0000000005', DATE'2020-10-04', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('user6', '1234', 'User6', '0', '0000000006', DATE'2020-10-04', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('user7', '1234', 'User7', '0', '0000000007', DATE'2020-10-04', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('user8', '1234', 'User8', '0', '0000000008', DATE'2020-10-04', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('user9', '1234', 'User9', '0', '0000000009', DATE'2020-10-04', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('user10', '1234', 'User10 WTF', '0', '0000000010', DATE'2020-10-04', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('legiao', '1234', 'Lê Giao', '0', '0987072222', DATE'2000-11-05', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('firefly', '1234', 'Th?ch Chí Tâm', '1', '0907070422', DATE'2000-07-09', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('chaubathong', '1234', 'Minh Thông', '1', '0987654321', DATE'1999-06-12', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('vovy', '1234', 'Vy Vy', '0', '0868685843', DATE'2000-03-31', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('mathew', '1234', 'Thành ??t', '1', '0246843333', DATE'2000-08-15', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('minhthu', '1234', 'Minh Th?', '0', '0758499229', DATE'2000-11-22', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('thambuoi', '1234', 'Nguy?n Th?m', '0', '0425165786', DATE'2000-08-27', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('congle', '1234', 'Công Công', '1', '0909988768', DATE'2000-02-28', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('ducquynh', '1234', 'Qu?nh ??c', '1', '0733445533', DATE'2000-08-30', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('thotho', '1234', 'V?n Th?', '1', '0584843828', DATE'2001-02-27', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('nhanduyen', '1234', 'Thành Nhân', '1', '0473625485', DATE'1998-07-13', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('nguyenngoc', '1234', 'Kh? Ái', '0', '0685473621', DATE'2005-09-19', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('khoinguyen', '1234', 'Lê Khôi', '1', '0678362522', DATE'2000-10-23', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('minhanh', '1234', 'Minh Ánh', '0', '0908070533', DATE'2000-04-12', 'default_avatar.png');

INSERT INTO BT_Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
VALUES('nguyetnga', '1234', 'Nguy?t Nga', '0', '0737222222', DATE'2000-01-15', 'default_avatar.png');

-- B?ng ph?ng
CREATE TABLE BT_Room
(
	"id" NUMBER(13,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, -- "id" ph?ng t? t?ng
    "name" NVARCHAR2(20) NOT NULL, -- Tên ph?ng
    datecreate TIMESTAMP DEFAULT SYSDATE NOT NULL, -- Ngày t?o ph?ng
    avatar VARCHAR(128) DEFAULT 'DEFAULT' NOT NULL, -- L?u ???ng d?n ?nh ??i di?n ph?ng
    
    -- Khóa chính
    CONSTRAINT BT_Room_PK PRIMARY KEY("id"),

    CONSTRAINT BT_Room_name_length_greaterThan2 CHECK (LENGTH("name")>2)
);

INSERT INTO BT_Room("name", datecreate)
VALUES('Phong 1', TIMESTAMP'2020-11-09 09:00:00');

INSERT INTO BT_Room("name")
VALUES('Ph?ng 2');

INSERT INTO BT_Room("name")
VALUES('Ph?ng 3');

INSERT INTO BT_Room("name")
VALUES('Ph?ng 4');

INSERT INTO BT_Room("name")
VALUES('Ph?ng 5');

INSERT INTO BT_Room("name")
VALUES('Ph?ng 6');

INSERT INTO BT_Room("name")
VALUES('Ph?ng 7');

INSERT INTO BT_Room("name")
VALUES('Ph?ng 8');

INSERT INTO BT_Room("name")
VALUES('Ph?ng 9');

INSERT INTO BT_Room("name")
VALUES('Ph?ng 10');

UPDATE BT_Room SET avatar = 'default_BT_Room_avatar.jpg' 
WHERE "id" < 11;

-- B?ng b?n bè
CREATE TABLE BT_Friend
(
	id_BT_Person NUMBER(13,0) NOT NULL,
	id_BT_Friend NUMBER(13,0) NOT NULL,
    isFriend NUMBER(1,0) DEFAULT 0 NOT NULL, -- 0 ?ang ch? k?t b?n
	adddate TIMESTAMP DEFAULT SYSDATE NOT NULL, -- Ngày thêm b?n
    
    -- Khóa ngo?i tham chi?u b?ng BT_Person
     CONSTRAINT BT_Friend_FK1_BT_Person FOREIGN KEY(id_BT_Person) REFERENCES BT_Person("id") ON DELETE CASCADE,
     CONSTRAINT BT_Friend_FK2_BT_Person FOREIGN KEY(id_BT_Friend) REFERENCES BT_Person("id"),
     
     -- Khóa chính
     CONSTRAINT Friens_PK PRIMARY KEY(id_BT_Person, id_BT_Friend)
);

-- User 1 là b?n c?a User 2  => User 2 là b?n c?a User 1
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend, isFriend)
VALUES('1', '2', '1');
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend, isFriend)
VALUES('2', '1', '1');

-- User 2 là b?n c?a User 3
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend, isFriend)
VALUES('2', '3', '1');
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend, isFriend)
VALUES('3', '2', '1');

-- User 2 g?i l?i m?i k?t b?n t?i user 4
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend)
VALUES('2', '4');
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend)
VALUES('4', '2');

-- User 2 g?i l?i m?i k?t b?n t?i user 5
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend)
VALUES('2', '5');
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend)
VALUES('5', '2');

-- User 2 là b?n c?a User 6
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend, isFriend)
VALUES('2', '6', '1');
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend, isFriend)
VALUES('6', '2', '1');

-- User 11 g?i l?i m?i k?t b?n t?i user 12
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend)
VALUES('11', '12');
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend)
VALUES('12', '11');

-- User 11 là b?n c?a User 13
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend)
VALUES('11', '13');
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend)
VALUES('13', '11');

-- User 11 là b?n c?a User 14
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend, isFriend)
VALUES('11', '14', '1');
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend, isFriend)
VALUES('14', '11', '1');

-- User 11 là b?n c?a User 15
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend, isFriend)
VALUES('11', '15', '1');
INSERT INTO BT_Friend(id_BT_Person, id_BT_Friend, isFriend)
VALUES('15', '11', '1');

-- B?ng danh sách ng??i dùng trong ph?ng
CREATE TABLE BT_Person_BT_Room
(
	id_BT_Room NUMBER(13,0), -- "id" ph?ng
    id_BT_Person NUMBER(13,0), -- "id" ng??i dùng
    intime TIMESTAMP DEFAULT SYSDATE NOT NULL, -- Th?i gian vào ph?ng m?c ??nh l?y gi? h? th?ng
	outtime TIMESTAMP DEFAULT SYSDATE NOT NULL, -- Th?i gian ra kh?i ph?ng  m?c ??nh l?y gi? h? th?ng 
    -- Khóa ngo?i
    -- B?ng BT_Room
    CONSTRAINT BT_Person_BT_Room_FK_BT_Room FOREIGN KEY(id_BT_Room) REFERENCES BT_Room("id") ON DELETE CASCADE,
    -- B?ng BT_Person
	CONSTRAINT BT_Person_BT_Room_FK_BT_Person FOREIGN KEY(id_BT_Person) REFERENCES BT_Person("id") ON DELETE CASCADE,
    
    -- Khóa chính
    CONSTRAINT BT_Person_BT_Room_PK PRIMARY KEY(id_BT_Room, id_BT_Person)
);

-- Ph?ng 1 có user 1, 2
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('1', '1');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('1', '2');

-- Ph?ng 2 có user 2, 3, 4, 5, 6
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('2', '2');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('2', '3');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('2', '4');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('2', '5');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('2', '6');

-- Ph?ng 3 có user 3, 5, 7, 9
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('3', '3');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('3', '5');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('3', '7');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('3', '9');


-- Ph?ng 4 có user 2, 4, 6, 8, 10
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('4', '2');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('4', '4');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('4', '6');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('4', '8');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('4', '10');

-- Ph?ng 5 có user 11, 12, 13, 14, 15, 16
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('5', '11');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('5', '12');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('5', '13');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('5', '14');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('5', '15');
INSERT INTO BT_Person_BT_Room(id_BT_Room, id_BT_Person)
VALUES('5', '16');

-- B?ng l?u tin nh?n c?a ph?ng ?ó t? ng??i dùng
CREATE TABLE BT_Message
(
	"id" NUMBER(13,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, -- "id"
	id_BT_Room NUMBER(13,0) NOT NULL, -- "id" ph?ng
    id_BT_Person NUMBER(13,0) NOT NULL, -- "id" ng??i dùng
	BT_Messagecontent NVARCHAR2(128) NOT NULL, -- N?i dung tin nh?n ho?c ???ng d?n file
    isFile NUMBER(1,0) DEFAULT 0 NOT NULL, -- Ki?m tra file m?c ??nh là tin nh?n
    sendtime TIMESTAMP DEFAULT SYSDATE NOT NULL, -- Th?i gian g?i tin nh?n m?c ??nh l?y gi? h? th?ng

	-- Khóa ngo?i
	-- B?ng BT_Room
    CONSTRAINT BT_Message_FK_BT_Room FOREIGN KEY(id_BT_Room) REFERENCES BT_Room("id") ON DELETE CASCADE,
    -- B?ng BT_Person
	CONSTRAINT BT_Message_FK_BT_Person FOREIGN KEY(id_BT_Person) REFERENCES BT_Person("id") ON DELETE CASCADE,
    
    -- Khóa chính
    CONSTRAINT BT_Message_PK PRIMARY KEY ("id")
);


-- User 1 g?i hello vào ph?ng 1
INSERT INTO BT_Message(id_BT_Room, id_BT_Person, BT_messagecontent, sendtime)
VALUES('1', '1', 'Hello', TIMESTAMP'2020-09-11 09:01:00');
-- User 2 g?i hallo vào ph?ng 1
INSERT INTO BT_Message(id_BT_Room, id_BT_Person, BT_messagecontent)
VALUES('1', '2', 'Hallo');
-- User 2 g?i hi vào ph?ng 1
INSERT INTO BT_Message(id_BT_Room, id_BT_Person, BT_messagecontent)
VALUES('1', '3', 'Hi');

-- Ph?ng 2
-- User 2 g?i ciao vào ph?ng 2
INSERT INTO BT_Message(id_BT_Room, id_BT_Person, BT_messagecontent)
VALUES('2', '2', 'Ciao');
-- User 3 g?i Osu vào ph?ng 2
INSERT INTO BT_Message(id_BT_Room, id_BT_Person, BT_messagecontent)
VALUES('2', '3', 'Osu');

-- Ph?ng 3
-- User 1 g?i xin chào vào ph?ng 3
INSERT INTO BT_Message(id_BT_Room, id_BT_Person, BT_messagecontent)
VALUES('3', '2', 'Xin chào');
-- User 3 g?i chào b?n vào ph?ng 3
INSERT INTO BT_Message(id_BT_Room, id_BT_Person, BT_messagecontent)
VALUES('3', '3', 'Chào b?n');




-------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------- Cau 2
-------------------------------------------------------------------------------------------------------------------------------------------------------


-- 2 thu tuc

CREATE OR REPLACE PROCEDURE spPerson_RemoveFriend(id_BT_Person INT, id_BT_Friend INT)
AS
BEGIN
    DELETE FROM BT_Friend f
    WHERE f.id_BT_Person = id_BT_Person AND f.id_BT_Friend = id_BT_Friend 
    OR f.id_BT_Person = id_BT_Friend AND f.id_BT_Friend = id_BT_Person;
END;

CREATE OR REPLACE PROCEDURE spMessage_DeleteMessage(id int)
AS
begin
delete from BT_Message where BT_Message."id" = id;
end;

-- 2 ham

CREATE OR REPLACE FUNCTION fcPerson_GetPopulation
RETURN NUMBER
IS
    cnt NUMBER(13,0);
BEGIN
   SELECT COUNT(*) INTO cnt FROM BT_Person;
   RETURN cnt;
END;

CREATE OR REPLACE FUNCTION fcRoom_GetRoomSize
RETURN NUMBER
IS
    cnt NUMBER(13,0);
BEGIN
   SELECT COUNT(*) INTO cnt FROM BT_Room;
   RETURN cnt;
END;

-- 2 trigger

CREATE TABLE BT_Person_Password_Log
(
    "id" NUMBER(13,0), 
    new_password VARCHAR(128) NOT NULL, 
    old_password VARCHAR(128) NOT NULL,
    modify_user VARCHAR2(100),
    modify_time TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE BT_Person_Name_Log
(
    "id" NUMBER(13,0),
    new_name VARCHAR(128) NOT NULL, 
    old_name VARCHAR(128) NOT NULL,
    modify_user VARCHAR2(100),
    modify_time TIMESTAMP DEFAULT SYSDATE
);

CREATE OR REPLACE TRIGGER BT_Person_Before_Update_Password
BEFORE UPDATE OF "password" ON BT_Person
FOR EACH ROW
BEGIN
   INSERT INTO BT_PERSON_Password_Log("id", new_password, old_password, modify_user) VALUES(:OLD."id", :NEW."password", :OLD."password", user);
END;

CREATE OR REPLACE TRIGGER BT_Person_Before_Update_Name
BEFORE UPDATE OF "name" ON BT_Person
FOR EACH ROW
BEGIN
   INSERT INTO BT_Person_Name_Log("id", new_name, old_name, modify_user) VALUES(:OLD."id", :NEW."name", :OLD."name", user);
END;

-------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------- Cau 3
-------------------------------------------------------------------------------------------------------------------------------------------------------


GRANT SELECT ON BT_Person TO "B1812326"
GRANT EXECUTE ON fcRoom_GetRoomSize TO "B1812326";
GRANT EXECUTE ON fcPerson_GetPopulation TO "B1812326";
GRANT EXECUTE ON spPerson_RemoveFriend TO "B1812326";
GRANT EXECUTE ON spMessage_DeleteMessage TO "B1812326";