-- T?o các b?ng (5 b?ng)
--DROP TABLE Person_Room;
--DROP TABLE Message;
--DROP TABLE FRIEND;
--DROP TABLE Person;
--DROP TABLE Room;

-- B?ng ngý?i dùng
CREATE TABLE Person
(
    "id" NUMBER(13,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, -- id t? tãng
    username VARCHAR(20) NOT NULL UNIQUE, -- Tài kho?n 
    "password" VARCHAR(128) NOT NULL, -- M?t kh?u lýu hash
    "name" NVARCHAR2(128) DEFAULT '1' NOT NULL, -- H? tên
    gender NUMBER(1,0) DEFAULT '0' NOT NULL, -- Gi?i tính 1 là nam 0 là n?
    phonenumber CHAR(10) UNIQUE NOT NULL, -- S? ði?n tho?i
    dateofbirth DATE DEFAULT SYSDATE NOT NULL, -- Ngày sinh
    avatar VARCHAR(128) DEFAULT 'DEFAULT' NOT NULL, -- Lýu ðý?ng d?n ?nh ð?i di?n ngý?i dùng
    
    -- Khóa chính
    CONSTRAINT Person_PK PRIMARY KEY ("id"),
    
    -- Các c?t
    CONSTRAINT Person_username_length_greaterThan2 CHECK (LENGTH(username)>2),
    CONSTRAINT Person_password_length_greaterThan2 CHECK (LENGTH("password")>2),
    CONSTRAINT Person_name_length_greaterThan2 CHECK (LENGTH("name")>2),
    CONSTRAINT Person_valid_phonenumber CHECK (REGEXP_LIKE(phonenumber,'^0\d{9}$'))
);


-- DROP TABLE Person;

--INSERT INTO Person(username, "password", "name", gender, phonenumber, dateofbirth, avatar)
-- VALUES('admin', '1234', 'Administrator', '1', '0000000000', DATE '2020-11-15' , 'anh-avatar-supreme-dep-lam-dai-dien-facebook.jpg');


-- B?ng ph?ng
CREATE TABLE Room
(
	"id" NUMBER(13,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, -- "id" ph?ng t? tãng
    "name" NVARCHAR2(20) NOT NULL, -- Tên ph?ng
    datecreate TIMESTAMP DEFAULT SYSDATE NOT NULL, -- Ngày t?o ph?ng
    avatar VARCHAR(128) DEFAULT 'DEFAULT' NOT NULL, -- Lýu ðý?ng d?n ?nh ð?i di?n ph?ng
    
    -- Khóa chính
    CONSTRAINT Room_PK PRIMARY KEY("id"),

    CONSTRAINT Room_name_length_greaterThan2 CHECK (LENGTH("name")>2)
);

--INSERT INTO Room("name", datecreate)
--VALUES('Phong 1', TIMESTAMP'2020-11-09 09:00:00');

-- B?ng b?n bè
CREATE TABLE Friend
(
	id_person NUMBER(13,0) NOT NULL,
	id_friend NUMBER(13,0) NOT NULL,
    isFriend NUMBER(1,0) DEFAULT 0 NOT NULL, -- 0 Ðang ch? k?t b?n
	adddate TIMESTAMP DEFAULT SYSDATE NOT NULL, -- Ngày thêm b?n
    
    -- Khóa ngo?i tham chi?u b?ng Person
     CONSTRAINT Friend_FK1_Person FOREIGN KEY(id_person) REFERENCES Person("id") ON DELETE CASCADE,
     CONSTRAINT Friend_FK2_Person FOREIGN KEY(id_friend) REFERENCES Person("id"),
     
     -- Khóa chính
     CONSTRAINT Friens_PK PRIMARY KEY(id_person, id_friend)
);

-- B?ng danh sách ngý?i dùng trong ph?ng
CREATE TABLE Person_Room
(
	id_room NUMBER(13,0), -- "id" ph?ng
    id_person NUMBER(13,0), -- "id" ngý?i dùng
    intime TIMESTAMP DEFAULT SYSDATE NOT NULL, -- Th?i gian vào ph?ng m?c ð?nh l?y gi? h? th?ng
	outtime TIMESTAMP DEFAULT SYSDATE NOT NULL, -- Th?i gian ra kh?i ph?ng  m?c ð?nh l?y gi? h? th?ng 
    -- Khóa ngo?i
    -- B?ng Room
    CONSTRAINT Person_Room_FK_Room FOREIGN KEY(id_room) REFERENCES Room("id") ON DELETE CASCADE,
    -- B?ng Person
	CONSTRAINT Person_Room_FK_Person FOREIGN KEY(id_person) REFERENCES Person("id") ON DELETE CASCADE,
    
    -- Khóa chính
    CONSTRAINT Person_Room_PK PRIMARY KEY(id_room, id_person)
);

-- B?ng lýu tin nh?n c?a ph?ng ðó t? ngý?i dùng
CREATE TABLE Message
(
	"id" NUMBER(13,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, -- "id"
	id_room NUMBER(13,0) NOT NULL, -- "id" ph?ng
    id_person NUMBER(13,0) NOT NULL, -- "id" ngý?i dùng
	messagecontent NVARCHAR2(128) NOT NULL, -- N?i dung tin nh?n ho?c ðý?ng d?n file
    isFile NUMBER(1,0) DEFAULT 0 NOT NULL, -- Ki?m tra file m?c ð?nh là tin nh?n
    sendtime TIMESTAMP DEFAULT SYSDATE NOT NULL, -- Th?i gian g?i tin nh?n m?c ð?nh l?y gi? h? th?ng

	-- Khóa ngo?i
	-- B?ng Room
    CONSTRAINT Message_FK_Room FOREIGN KEY(id_room) REFERENCES Room("id") ON DELETE CASCADE,
    -- B?ng Person
	CONSTRAINT Message_FK_Person FOREIGN KEY(id_person) REFERENCES Person("id") ON DELETE CASCADE,
    
    -- Khóa chính
    CONSTRAINT Message_PK PRIMARY KEY ("id")
);




